### ISSUE TITLE
Continue to use WebSocket?

### ISSUE THREAD

**Issue by KradekMFC** [KradekMFC/MFCSocket#2]
Not sure if MFCSocket actually needs to use a WebSocket anymore; could probably convert it over to use plain node net libraries. Websocket is a remnant of when MFCSocket was originally designed to work as a browser library.

Not sure if the overhead of using a Websocket instead of a plain old socket is worth worrying about though.

Also, could support two versions, one for node, one for browsers.

**Comment by Temptin** [comment]
@KradekMFC Just some thoughts on that: Their site is gradually modernizing to being mobile-ready/html5/websockets all over the place, and within a year or two (when Flash is truly dead) they may even retire all other communication methods. So a websocket library is definitely needed.

And hey, good news! I discovered the cause of ws >0.7.1 breaking! It's two things! The first is extra validation on MFC's side to make sure our socket connection "comes from a client viewing the main website". All we need to do is fake it by changing the connection statement to pass an "origin" parameter (which is a value describing what website initiated the connection). I tried different values and they're only happy when their domain name is in the origin. Here is what I'm doing in the MFCSocket library now:

``` javascript
new WebSocket( serverUrl, {
            protocolVersion: 13, // rfc6455; current default in the ws library, but we're enforcing it anyway
            origin: 'http://m.myfreecams.com', // pretend that we're connecting to the ws server from the mobile site (this is required, because they validate on the server-side that the Origin header ends in "myfreecams.com")
        });
```

The second reason for the breakage is also easy to fix: You know the list of servers you're retrieving? Make sure you only extract/connect to servers with the "rfc6455" value. They have one or two super old hybi00 servers (for people with old browsers), which is not supported by the node-ws client library.

With these two changes it's possible to use ws >=0.7.2!

I would contribute a pull request but I've rewritten 100% of the MFCSocket code so it wouldn't be compatible.

**Comment by Temptin** [comment]
Actually, here's the code I use to extract only rfc6455 servers:

``` javascript
for( var k in mfcServerConfig.websocket_servers ){
    if( mfcServerConfig.websocket_servers.hasOwnProperty( k ) ){
        if( mfcServerConfig.websocket_servers[k] == 'rfc6455' ){
            _state.serverList.websocketServers.push( k ); // save only the key (the server name, such as "xchat10")
        }
    }
}
```

**Comment by Temptin** [comment]
Forgot this one:

> Not sure if the overhead of using a Websocket instead of a plain old socket is worth worrying about though.

No worries. There's almost no noticeable overhead. The ws library is written in C++ and can deal with thousands of connections at once, each sending loads of messages. A single MFC socket won't slow things down. ;-)

**Comment by KradekMFC** [comment]
@Temptin I didn't figure there would be much overhead. This was generally just something I was mulling over as I was making some of the other changes.

Thanks for the info with respect to the sockets. I'll update sometime this weekend probably.

**Comment by Temptin** [comment]
@KradekMFC Happy to help! ;-)

**Comment by KradekMFC** [comment]
For now, sticking with websockets.
